services:
  e2etests:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["sh", "-c", "mvn test && allure serve"]
    working_dir:  /e2etests
    volumes:
      - ./:/e2etests/