name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    - name: Ensure Docker Compose is installed
      run: docker-compose --version || sudo apt-get install -y docker-compose
    - name: Download Docker images
      run: docker-compose pull

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages  
    
    - name: Run tests
      run: docker-compose run --rm e2etests

    - name: Test here and host elsewhere
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        github_repo: wcalmonqa/commit-quality-java/
        github_repo_owner: wcalmonqa

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history  