name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
    - name: Ensure Docker Compose is installed
      run: docker-compose --version || sudo apt-get install -y docker-compose
    - name: Download Docker images
      run: docker-compose pull
    - name: Run tests
      run: docker-compose run --rm e2etests